version: '3.9'

services:
  jupyter:
    image: jupyter/datascience-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS='-R'
      - NB_UID=1000
      - NB_GID=1000
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped
