repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        pass_filenames: false
        args:
          [
            "-rn",
            "-sn",
            "--rcfile=post/app/.pylintrc",
            "--load-plugins=pylint.extensions.docparams",
            "post/app",
          ]
        
